services:
  - type: web
    name: chessplay-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.20.2
      - key: NODE_ENV
        value: production
