export const designTokens = {
  spacing: {
    0: "var(--space-0)",
    1: "var(--space-1)",
    2: "var(--space-2)",
    3: "var(--space-3)",
    4: "var(--space-4)",
    5: "var(--space-5)",
    6: "var(--space-6)",
    8: "var(--space-8)",
    10: "var(--space-10)",
    12: "var(--space-12)",
    16: "var(--space-16)",
    20: "var(--space-20)",
  },
  radius: {
    xs: "var(--radius-xs)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    "2xl": "var(--radius-2xl)",
    "3xl": "var(--radius-3xl)",
    full: "var(--radius-full)",
  },
  typography: {
    sans: "var(--font-sans)",
    display: "var(--font-display)",
    mono: "var(--font-mono)",
    sizes: {
      xs: "var(--text-xs)",
      sm: "var(--text-sm)",
      base: "var(--text-base)",
      lg: "var(--text-lg)",
      xl: "var(--text-xl)",
      "2xl": "var(--text-2xl)",
      "3xl": "var(--text-3xl)",
    },
    lineHeight: {
      tight: "var(--leading-tight)",
      body: "var(--leading-body)",
    },
  },
  shadows: {
    xs: "var(--shadow-xs)",
    sm: "var(--shadow-sm)",
    md: "var(--shadow-md)",
    lg: "var(--shadow-lg)",
    glow: "var(--shadow-glow)",
  },
  zIndex: {
    base: "var(--z-base)",
    content: "var(--z-content)",
    nav: "var(--z-nav)",
    overlay: "var(--z-overlay)",
    modal: "var(--z-modal)",
    tooltip: "var(--z-tooltip)",
  },
  transitions: {
    fast: "var(--duration-fast) var(--ease-standard)",
    normal: "var(--transition-ui)",
    slow: "var(--duration-slow) var(--ease-spring)",
  },
  colors: {
    primary: "var(--color-primary)",
    primaryStrong: "var(--color-primary-strong)",
    primaryContrast: "var(--color-primary-contrast)",
    background: {
      primary: "var(--color-bg-primary)",
      secondary: "var(--color-bg-secondary)",
      tertiary: "var(--color-bg-tertiary)",
      elevated: "var(--color-bg-elevated)",
      glass: "var(--color-bg-glass)",
    },
    surface: "var(--color-surface)",
    surfaceStrong: "var(--color-surface-strong)",
    text: {
      primary: "var(--color-text-primary)",
      secondary: "var(--color-text-secondary)",
      tertiary: "var(--color-text-tertiary)",
    },
    border: {
      primary: "var(--color-border-primary)",
      strong: "var(--color-border-strong)",
    },
    focus: "var(--color-focus)",
    success: "var(--color-success)",
    warning: "var(--color-warning)",
    danger: "var(--color-danger)",
    info: "var(--color-info)",
  },
};

export default designTokens;
